### ISSUE TITLE
box.slarmoo.com is now a Simon Says game

### ISSUE THREAD

**Issue by wdym-lmao** [slarmoo/slarmoosboxtesting#1]
I don't know if you're the owner of this website, but this has been happening for a few days now. It would be nice if you could port SB 1.3.1 to this if you do happen to own this domain.

**Comment by slarmoo** [comment]
Sorry that domain is for my personal use and I'd rather that you didn't use it. Please use slarmoo.github.io/slarmoosbox instead, thank you!
